server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/platform_auth
    username: auth_user
    password: auth_pass

  data:
    redis:
      host: redis
      port: 6379
